# Generated by Django 4.0.4 on 2022-05-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourdebt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='amount_owed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='int_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
