# Generated by Django 4.0.4 on 2022-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourdebt', '0003_debt_mortgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='time_topay',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
