# Generated by Django 4.0.4 on 2022-05-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourdebt', '0004_debt_time_topay'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='extra_principal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='min_payment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
