# Generated by Django 4.0.4 on 2022-05-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourdebt', '0006_closedebt_mortgage_opendebt_delete_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='mortgage_term',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
